### PR TITLE
update(README.md)

### PR DESCRIPTION
**Pull request by shahabganji**
Adding a link to related modules for an Aurelia value converter which uses humanizeDuration.

### CODE REVIEW

**Comment by shahabganji** [comment]
Dear @EvanHahn ,
I just updated the README.md file, and have no idea why travis didn't pass as it doesn't say anything in the log files, may I ask you to take a look.

Best regards,
Shahab

**Comment by EvanHahn** [comment]
I'll take a look at this by November 10.

Thanks!

**Comment by shahabganji** [comment]
That's good buddy,
Thanks

**Comment by EvanHahn** [comment]
Thanks! Merged.

**Comment by shahabganji** [comment]
Thank you 👍

**Pull request merged**
