### PR TITLE
Arabic Localization Fix "minutes" 

### PR DESCRIPTION
**Pull request by A-ezzat1997**
In Arabic language we have more than one condition to show "دقيقة" (minute) or "دقائق" (minutes)  this pull request fixes that issue according to Arabic grammar and rules.

### CODE REVIEW

**Comment by EvanHahn** [comment]
Could you also change the tests to make them pass?

**Comment by A-ezzat1997** [comment]
@EvanHahn  yeah sure, you can see now that the test passes and I've edited the test cases result

**Comment by EvanHahn** [comment]
Thanks! I am a bit busy right now but will take a look soon.

**Comment by A-ezzat1997** [comment]
@EvanHahn  any updates about this one :'D ?

**Comment by A-ezzat1997** [comment]
@EvanHahn  I've deleted my comments, sorry for being late

**Comment by EvanHahn** [comment]
Thanks! I will deploy a new version in the next week.

**Comment by EvanHahn** [comment]
Deployed `humanize-duration@3.15.2` with this change. Thank you!

**Pull request merged**
