### PR TITLE
Update length of month and year

### LINKED ISSUE #156: Calculations of years and months wrong due to leap year
The constants uses for milliseconds in a year and milliseconds in a month are incorrect because they are computed from the slightly naïve understanding of leap days in the Gregorian calendar.

A leap day occurs every four years. However, because that's actually slightly too often, if the year is divisible by 100 then it *is not* a leap year. *However*, because _that_ would be too infrequent, if the year is divisible by 400 they it *is* a leap year.

Thus the correct decimal representation of the _average_ length of a year is `365.2425` days. Likewise, since the year is 12 exact months, an _average_ length of a month is `30.436875` days.

### PR DESCRIPTION
**Pull request by IDisposable**
Since leap years are actually every four years EXCEPT every hundred years but INCLUDING every four-hundred years, the average number of days in a year is `365.2425` not `365.25`. This means that the number of days in a month is (on average) `30.436875` days.

This means we have to update all the test data to conform to the correct calculations.

Fixes #156

### CODE REVIEW

**Comment by EvanHahn** [comment]
Mentioned some concerns in #156—let's discuss there unless it's about this fix specifically.

**Comment by motchju** [comment]
Would be nice to merge it, thanks @IDisposable for the work

**Comment by EvanHahn** [comment]
For anyone following along here but not in the original issue, [I added a comment](https://github.com/EvanHahn/HumanizeDuration.js/issues/156#issuecomment-640253064) explaining my plans here.

**Comment by EvanHahn** [comment]
I just renamed `master` to `main` which caused this PR to be automatically closed. I didn't realize this would happen. Apologies!

**Pull request closed without merging**
