### PR TITLE
Improve Arabic & convert to arabic numbers

### PR DESCRIPTION
**Pull request by Misioka**
In some cases like e.g. react-native Number.toLocaleString is not working. That's why I have added the convert function to the dictionary.

### CODE REVIEW

**Comment by EvanHahn** [comment]
Does `npm test` pass after this change? Should you update the Arabic test CSV file?

**Comment by Misioka** [comment]
@EvanHahnI have updated CSV and now all tests passes.

**Comment by EvanHahn** [comment]
Thanks! I'll take a look soon.

**Comment by EvanHahn** [comment]
Thanks! I am going to make some changes in #199 and will merge soon.

**Comment by EvanHahn** [comment]
This has been deployed in `humanize-duration@3.27.0`. Thanks again!

I would like to add you to the contributors list. What name and URL should I use?

**Comment by Misioka** [comment]
Thanks a lot for your work.

I will be honored to become a contributor.
You can use the GitHub link https://github.com/Misioka
And my name is Michal Karzel

**Comment by EvanHahn** [comment]
I just credited you in 8e03ec0bfc215c4ed48aca250c86ae81c61ccc3b. Thanks again!

**Pull request merged**
