### PR TITLE
replace var into const in README

### PR DESCRIPTION
**Pull request by oprogramador**

### CODE REVIEW

**Comment by EvanHahn** [comment]
Thanks! Do you think it's worth putting arrow functions in the readme, too?

**Comment by piotr-s-brainhub** [comment]
@EvanHahn yes, IMO arrow functions are more readable

**Comment by oprogramador** [comment]
@evo

**Comment by EvanHahn** [comment]
Would you mind submitting another pull request?

**Comment by oprogramador** [comment]
@EvanHahn yes, IMO arrow functions are more readable

**Comment by oprogramador** [comment]
@EvanHahn 
I did that in https://github.com/EvanHahn/HumanizeDuration.js/pull/138

**Pull request merged**
