### PR TITLE
Add Central Kurdish branch (CKB) language

### PR DESCRIPTION
**Pull request by Xoshbin**

### CODE REVIEW

**Comment by EvanHahn** [comment]
Thank you. I will review soon.

**Comment by EvanHahn** [comment]
The tests fail. Try running `npm test` to fix this issue.

It looks like the problem is with `86400000` milliseconds, among others.

**Comment by Xoshbin** [comment]
Passed all the tests, sorry for the late reply and thank you.

**Comment by EvanHahn** [comment]
This has been published in `humanize-duration@3.31.0`. Thank you!

**Pull request merged**
