### PR TITLE
Add Hindi language support

### PR DESCRIPTION
**Pull request by aryanrawlani28**
Hello!

I've added Hindi language support. Can you review it?

Thanks a lot! :)

### CODE REVIEW

**Comment by EvanHahn** [comment]
Thanks! I'll review this soon.

**Comment by EvanHahn** [comment]
I plan to deploy this in the next few days.

**Comment by EvanHahn** [comment]
This has been released in `humanize-duration@3.24.0`. Thanks again!

**Comment by aryanrawlani28** [comment]
Thank you also!

**Pull request merged**
