### PR TITLE
support( Farsi/Persian language )

### PR DESCRIPTION
**Pull request by shahabganji**
Adding the "fa" for Persian/Farsi languages in the languages dictionary

### CODE REVIEW

**Comment by EvanHahn** [comment]
_متشکرم!_

This is in version 3.11.0.

Can I add you to [the credits list](https://github.com/EvanHahn/HumanizeDuration.js#credits)?

**Comment by shahabganji** [comment]
@EvanHahn  خواهش میکنم!

Thanks for your time and effort, that would be an honor 👍

**Comment by EvanHahn** [comment]
What name and URL should I use?

**Comment by shahabganji** [comment]
Saeed Ganji as username and my github page as URL 👍🏻👍🏻

**Comment by EvanHahn** [comment]
[Done!](https://github.com/EvanHahn/HumanizeDuration.js/commit/93970de227b92db52e1c2010e9c98b56f6f46e2d) Thanks again.

**Comment by shahabganji** [comment]
Thank YOU 😊

**Pull request merged**
